#!/bin/sh
#husky 0.14.3
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop staging test)
fi

# Get the current branch name and check if it is excluded
BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")

# Trim it down to get the parts we're interested in excape slashes to add entire branch name to commit
TRIMMED=$(echo $BRANCH_NAME | sed -e "s/\//\\\\\//")

# If it isn't excluded, preprend the trimmed branch identifier to the given message
if [ -n "$BRANCH_NAME" ] &&  ! [[ $BRANCH_EXCLUDED -eq 1 ]]; then
  sed -i -e "1s/^/$TRIMMED | /" $1
  # sed -i.bak -e "1s/^/$BRANCH_NAME | /" $1
fi
